name: Publish Package to github npm
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: vars
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com"
      - run: npm ci
      - run: npm run build
      - run: cp package.json dist/
      - run: npm publish dist/ --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.API_PUBLISH_KEY }}
